title: Preston Whaley
email: Pw463@cornell.edu
description: >-
  Preston Whaley is a mechanical engineer and a self-taught programmer. He specialises in robotic mechanical design and is passionate about autonomous systems. 
baseurl: ""
url: "https://PrestonWhaley.github.io"
google_analytics: "G-GSRER1MM23"

collections:
  projects:
    permalink: /project/:name
    output: true
  achievements:
    permalink: /achievement/:name
    output: true

defaults:
  - scope:
      path: "_projects/*.md"
    values:
      layout: project
  - scope:
      path: "_achievements/*.md"
    values:
      layout: achievement

plugins:
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-minifier
  - jekyll-hostname
  - jekyll-hashsert

jekyll-minifier:
  exclude:
    - "sitemap.xml"
    - "assets/css/theme.css"
  uglifier_args:
    harmony: true

extlinks:
  attributes: { rel: nofollow noopener noreferrer, target: _blank }
  rel_include: [ "l.prestonwhaley.github.io" ]
  rel_exclude: [ "prestonwhaley.github.io", "github.com" ]

include:
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
